version: "3.9"
services:
  app:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_URL_EXPIRE_SECONDS=3600
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/app?sslmode=disable
      - POSTGRES_URL_EXPIRE_SECONDS=604800
      - POPULAR_URL_TIMELAPSE_MINS=15
      - PORT=:8000
      - HOSTNAME=http://127.0.0.1:8000

  migrate:
    image: migrate/migrate
    volumes:
        - ./db/migrations:/migrations
    command: [
      "-path", "/migrations", "-database",
      "postgres://postgres:postgres@postgres:5432/app?sslmode=disable", "up"
    ]

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app

  redis:
    image: redis
    volumes:
      - ./redis-data:/var/lib/redis
    ports:
      - "6379:6379"

